version: '3'

services:

    frontend:
        container_name: frontChatbot
        stdin_open: true
        build:
            context: ./Front-end
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        # volumes:
        #     - "/usr/Front-end"

    backend:
        container_name: back-Chatbot
        build:
            context: ./Back-end
            dockerfile: Dockerfile
        ports:
            - "3001-3001"
        # volumes:
        #     - "/usr/Back-end"
